sudo: required
services:
  - docker

before_install:
  - docker build -t akosfi/imager-backend .

script:
  - docker run akosfi/imager-backend npm run test

jobs:
  include:
    - stage: log
      script:
        - docker run akosfi/imager-backend npm run log

stages:
  - name: log
    if: branch = master