sudo: required
services:
  - docker

before_install:
  - docker build -t akosfi/imager-backend .

script:
  - docker run akosfi/imager-backend npm run test

jobs:
  include:
    - stage: log
      script:
        - docker run akosfi/imager-backend npm run log
    - stage: lint
      script:
        - docker run akosfi/imager-backend npm run lint
    - stage: test
      script:
        - docker run akosfi/imager-backend npm run test
    - stage: deploy
      script:
        - docker run akosfi/imager-backend npm run log

stages:
  - log
  - lint
  - test
  - name: deploy
    if: (type = push AND branch IN (master, staging))