sudo: required
services:
  - docker

before_install:
  - docker build -t akosfi/imager-backend .

script:
  - docker run akosfi/imager-backend npm run test

stages:
  - name: deploy
    if: branch = master
      - docker run akosfi/imager-backend npm run log