on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t akosfi/imager-backend:latest .
      - name: Lint
        run: docker run akosfi/imager-backend npm run lint
      - name: Test
        run: docker run akosfi/imager-backend npm run test