on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the tagged Docker image
        run: docker build -t akosfi/imager-backend .

      - name: Get the output time
        run: echo "Echo example."